  
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  install:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    needs: install
    steps:
      - run: npm test
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x]
    needs: [install, test]
    steps:
      - run: npm run-script build --prod
  deploy:
    runs-on: self-hosted
    needs: [install, test, build]
    steps:
      - run: .github/workflows/deploy_front.sh